export const US_INDICES = [
  { symbol: '^GSPC', name: '标普 500', group: '指数' },
  { symbol: '^DJI', name: '道琼斯', group: '指数' },
  { symbol: '^IXIC', name: '纳斯达克', group: '指数' },
  { symbol: '^SOX', name: '费城半导体', group: '指数' },
  { symbol: '^VIX', name: 'VIX 恐慌', group: '指数' },
];

export const US_WATCHLIST = [
  { symbol: 'AAPL', name: 'Apple', group: '科技巨头', summary: '消费电子与自研芯片' },
  { symbol: 'MSFT', name: 'Microsoft', group: '科技巨头', summary: '云与 AI 应用层' },
  { symbol: 'NVDA', name: 'NVIDIA', group: '科技巨头', summary: 'GPU / AI 算力' },
  { symbol: 'GOOGL', name: 'Alphabet', group: '科技巨头', summary: '搜索、云与自研 TPU' },
  { symbol: 'AMZN', name: 'Amazon', group: '科技巨头', summary: '云与电商' },
  { symbol: 'META', name: 'Meta', group: '科技巨头', summary: '社交与 AI 推荐' },
  { symbol: 'TSLA', name: 'Tesla', group: '科技巨头', summary: '电动车与具身智能' },
  { symbol: 'AVGO', name: 'Broadcom', group: '算力链', summary: '交换 ASIC / 光模块 DSP' },
  { symbol: 'TSM', name: '台积电', group: '算力链', summary: '晶圆代工' },
  { symbol: 'AMD', name: 'AMD', group: '算力链', summary: 'GPU / CPU' },
  { symbol: 'MU', name: '美光', group: '算力链', summary: 'HBM 与存储' },
  { symbol: 'INTC', name: 'Intel', group: '算力链', summary: 'CPU / 晶圆制造' },
  { symbol: 'MRVL', name: 'Marvell', group: '算力链', summary: '数据中心 ASIC / DSP' },
  { symbol: 'ARM', name: 'Arm', group: '算力链', summary: '芯片 IP' },
  { symbol: 'QCOM', name: '高通', group: '算力链', summary: '手机 / 边缘 AI' },
  { symbol: 'GFS', name: '格芯', group: '算力链', summary: '特色代工' },
  { symbol: 'AMKR', name: 'Amkor', group: '算力链', summary: '封测' },
  { symbol: 'ASX', name: '日月光', group: '算力链', summary: '先进封装' },
  { symbol: 'COHR', name: 'Coherent', group: '光模块', summary: '激光 / 光器件' },
  { symbol: 'LITE', name: 'Lumentum', group: '光模块', summary: '光通信器件' },
  { symbol: 'AAOI', name: '应用光电', group: '光模块', summary: '光模块' },
  { symbol: 'FN', name: 'Fabrinet', group: '光模块', summary: '光模块代工' },
  { symbol: 'CRDO', name: 'Credo', group: '光模块', summary: '高速连接' },
  { symbol: 'ALAB', name: 'Astera Labs', group: '光模块', summary: '高速连接' },
  { symbol: 'MTSI', name: 'MACOM', group: '光模块', summary: '射频 / 光通信' },
  { symbol: 'ASML', name: 'ASML', group: '半导体设备', summary: '光刻' },
  { symbol: 'AMAT', name: '应用材料', group: '半导体设备', summary: '薄膜 / 沉积' },
  { symbol: 'LRCX', name: '泛林', group: '半导体设备', summary: '刻蚀' },
  { symbol: 'KLAC', name: 'KLA', group: '半导体设备', summary: '检测量测' },
  { symbol: 'TER', name: '泰瑞达', group: '半导体设备', summary: '测试' },
  { symbol: 'ACLS', name: 'Axcelis', group: '半导体设备', summary: '离子注入' },
  { symbol: 'TXN', name: '德州仪器', group: '模拟功率', summary: '模拟芯片' },
  { symbol: 'ADI', name: '亚德诺', group: '模拟功率', summary: '模拟 / 混合信号' },
  { symbol: 'MPWR', name: '芯源系统', group: '模拟功率', summary: 'AI 服务器电源管理' },
  { symbol: 'NXPI', name: '恩智浦', group: '模拟功率', summary: '汽车芯片' },
  { symbol: 'MCHP', name: '微芯', group: '模拟功率', summary: 'MCU' },
  { symbol: 'ON', name: '安森美', group: '模拟功率', summary: '功率半导体' },
  { symbol: 'ENTG', name: 'Entegris', group: '材料', summary: '半导体特材 / 过滤' },
  { symbol: 'ROG', name: 'Rogers', group: '材料', summary: '高频覆铜板材料' },
  { symbol: 'MKSI', name: 'MKS', group: '材料', summary: '工艺气体、真空、激光' },
  { symbol: 'TTMI', name: 'TTM', group: 'PCB', summary: 'PCB 制造' },
  { symbol: 'SANM', name: 'Sanmina', group: 'PCB', summary: 'PCB + 系统组装' },
  { symbol: 'GLW', name: '康宁', group: '光纤玻璃', summary: '光纤 + 特种玻璃' },
  { symbol: 'APH', name: '安费诺', group: '光纤玻璃', summary: '连接器 / 光连接' },
  { symbol: 'TEL', name: '泰科', group: '光纤玻璃', summary: '连接器' },
  { symbol: 'IPGP', name: 'IPG', group: '光纤玻璃', summary: '光纤激光' },
  { symbol: 'SMCI', name: '超微', group: 'AI下游', summary: 'AI 服务器' },
  { symbol: 'DELL', name: 'Dell', group: 'AI下游', summary: 'AI 服务器' },
  { symbol: 'VRT', name: 'Vertiv', group: 'AI下游', summary: '液冷 / 数据中心电力' },
  { symbol: 'CLS', name: 'Celestica', group: 'AI下游', summary: 'AI 服务器 / 交换机代工' },
  { symbol: 'ORCL', name: 'Oracle', group: 'AI下游', summary: '云与数据库' },
  { symbol: 'PLTR', name: 'Palantir', group: 'AI下游', summary: 'AI 应用' },
  { symbol: 'SMH', name: '半导体 ETF', group: 'ETF', summary: 'VanEck 半导体' },
  { symbol: 'SOXX', name: '费城半导体 ETF', group: 'ETF', summary: 'iShares 跟踪 SOX' },
  { symbol: 'SOXL', name: 'SOXL', group: 'ETF', summary: '费城半导体 3 倍做多' },
  { symbol: 'SPY', name: '标普 500 ETF', group: 'ETF', summary: '标普 500' },
  { symbol: 'QQQ', name: '纳指 100 ETF', group: 'ETF', summary: '纳指 100' },
  { symbol: 'IWM', name: '罗素 2000 ETF', group: 'ETF', summary: '罗素 2000' },
];

export const US_GROUPS = ['全部', '科技巨头', '算力链', '光模块', '半导体设备', '模拟功率', '材料', 'PCB', '光纤玻璃', 'AI下游', 'ETF', '自选'];
