import {
  HARNESS_DEFAULT_MODEL,
  HARNESS_ELUCID_DEFAULT_BASE_URL,
  HARNESS_ELUCID_DEFAULT_MODEL,
  HARNESS_ELUCID_PROVIDER,
  HARNESS_PROVIDER,
} from './constants.js';

function text(value) {
  return typeof value === 'string' && value.trim() ? value.trim() : '';
}

function yamlString(value) {
  return JSON.stringify(String(value ?? ''));
}

function modelIdForProfile(defaultModel, researchModel, researchProfile) {
  const fallback = text(defaultModel);
  if (researchProfile?.modelProfile !== 'research') return fallback;
  return text(researchModel) || fallback;
}

export function resolveHarnessLlmProvider(env = process.env) {
  const id = text(env.AI_CENTER_HARNESS_PROVIDER).toLowerCase();
  if (id === 'elucid' || id === 'elucid-grok' || id === 'grok') return HARNESS_ELUCID_PROVIDER;
  return HARNESS_PROVIDER;
}

export function resolveHarnessLlm(env = process.env, { researchProfile } = {}) {
  const provider = resolveHarnessLlmProvider(env);
  const elucidKeyEnv = text(env.ELUCID_GROK_API_KEY)
    ? 'ELUCID_GROK_API_KEY'
    : (text(env.AI_CENTER_GROK_API_KEY) ? 'AI_CENTER_GROK_API_KEY' : 'ELUCID_GROK_API_KEY');
  const elucidBaseURL = (text(env.AI_CENTER_ELUCID_GROK_API_ROOT) || HARNESS_ELUCID_DEFAULT_BASE_URL)
    .replace(/\/+$/, '');
  const deepseekBaseURL = text(env.DEEPSEEK_BASE_URL).replace(/\/+$/, '');
  const elucidDefaultModel = text(env.AI_CENTER_HARNESS_MODEL) || HARNESS_ELUCID_DEFAULT_MODEL;
  const deepseekDefaultModel = text(env.AI_CENTER_HARNESS_MODEL) || HARNESS_DEFAULT_MODEL;
  const researchModel = text(env.AI_CENTER_HARNESS_RESEARCH_MODEL);
  const defaultModel = provider === HARNESS_ELUCID_PROVIDER ? elucidDefaultModel : deepseekDefaultModel;
  const model = modelIdForProfile(defaultModel, researchModel, researchProfile);
  const apiKeyEnv = provider === HARNESS_ELUCID_PROVIDER ? elucidKeyEnv : 'DEEPSEEK_API_KEY';
  return {
    provider,
    model,
    defaultModel,
    researchModel,
    apiKeyEnv,
    apiKey: text(env[apiKeyEnv]),
    baseURL: provider === HARNESS_ELUCID_PROVIDER ? elucidBaseURL : deepseekBaseURL,
    protocol: provider === HARNESS_ELUCID_PROVIDER ? 'openai-responses' : '',
    settingsYaml: materializeHarnessSettings({
      elucidKeyEnv,
      elucidBaseURL,
      deepseekBaseURL,
      models: [...new Set([
        elucidDefaultModel,
        deepseekDefaultModel,
        researchModel,
        model,
      ].filter(Boolean))],
    }),
  };
}

export function missingHarnessLlmCredential(env = process.env, llm = resolveHarnessLlm(env)) {
  return !text(llm?.apiKey);
}

export function harnessLlmCredentialError(llm) {
  if (llm?.provider === HARNESS_ELUCID_PROVIDER) {
    return `Harness runtime 需要 ${llm.apiKeyEnv || 'ELUCID_GROK_API_KEY'}`;
  }
  return 'Harness runtime 需要 DEEPSEEK_API_KEY';
}

export function materializeHarnessSettings({
  elucidKeyEnv,
  elucidBaseURL,
  deepseekBaseURL,
  models = [HARNESS_ELUCID_DEFAULT_MODEL, HARNESS_DEFAULT_MODEL],
} = {}) {
  const ids = [...new Set((models.length ? models : [HARNESS_ELUCID_DEFAULT_MODEL]).map((id) => text(id)).filter(Boolean))];
  const modelLines = ids.map((id) => `        - id: ${yamlString(id)}`).join('\n');
  const deepseek = [
    'llm-deepseek:',
    `  apiKeyEnv: ${yamlString('DEEPSEEK_API_KEY')}`,
  ];
  if (text(deepseekBaseURL)) deepseek.push(`  baseURL: ${yamlString(deepseekBaseURL)}`);
  return [
    '# Generated by AI Center. Credential values stay in the environment, not this file.',
    ...deepseek,
    'llm-pi-ai:',
    '  providers:',
    `    ${HARNESS_ELUCID_PROVIDER}:`,
    `      apiKeyEnv: ${yamlString(elucidKeyEnv || 'ELUCID_GROK_API_KEY')}`,
    '      api: openai-responses',
    `      baseURL: ${yamlString(elucidBaseURL || HARNESS_ELUCID_DEFAULT_BASE_URL)}`,
    '      displayName: Elucid Grok',
    '      models:',
    modelLines,
    '',
  ].join('\n');
}

export function materializeElucidSettings(options = {}) {
  return materializeHarnessSettings(options);
}
